steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread-repo/app'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread-repo/app'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'app'
      - '--image'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread-repo/app'
      - '--region'
      - 'eu-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread-repo/app'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET