steps:
  # Authenticate Docker with Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - 'gcloud auth configure-docker eu-west2-docker.pkg.dev'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread/app'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread/app'

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'app'
      - '--image'
      - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread/app'
      - '--region'
      - 'eu-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'eu-west2-docker.pkg.dev/${PROJECT_ID}/artisan-thread/app'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
